### ISSUE TITLE
Add repo topics

### ISSUE THREAD

**Issue by aschrijver** [joyeusenoelle/GuideToMastodon#11]
Hi,

You have a great guide going on here, congrats. May I suggest that for increased findability you add some topic labels to the repo, like 'mastodon', 'fediverse', 'activitypub', 'activitystreams', 'decentralization', etc.?

**Comment by joyeusenoelle** [comment]
I didn't know I could do that, and have done so! Thank you!

**Comment by aschrijver** [comment]
Great, thx! Fediverse rocks :)

PS. I added a link to your guide in the [SocialHub wiki post](https://socialhub.activitypub.rocks/t/guide-for-activitypub-users/509#more-information) that is also collecting AP user-targeted info.
