### ISSUE TITLE
Mention account migration

### ISSUE THREAD

**Issue by progval** [joyeusenoelle/GuideToMastodon#22]
Hi,

Since this guide was written, Mastodon added support for migrating accounts. In particular, migrating followers.

this should probably be mentioned somewhere, maybe in https://github.com/joyeusenoelle/GuideToMastodon#how-do-i-pick-an-instance

**Comment by joyeusenoelle** [comment]
Thank you for bringing this up - it's been on my mind to add something about that, but I keep back-burnering it because I want to remind myself of how it works before I say anything. But you've prompted me to make the effort sooner rather than later. :)
