### ISSUE TITLE
Additional details for the "How do privacy settings work?" section

### ISSUE THREAD

**Issue by codesections** [joyeusenoelle/GuideToMastodon#3]
I think it would be helpful to have additional details in the "How do privacy settings work?" section, since there are several features that aren't documented here.  For example, DMs and follower-only toots are locked from being boosted, but others may be boosted.

I would have submitted this as a pull request instead of an issue, but there are still several areas related to privacy settings that confuse me.  For example, how do privacy settings work with replies?  My understanding is that replies aren't shown on the local timeline at all—does this mean that Public and Unlisted replies are exactly the same?  Or is there still some difference?  Or is whether replies are sent to the local timeline something that instance admins configure?

**Comment by joyeusenoelle** [comment]
Good questions! I'll try to make sure I understand them myself and then update the guide.

**Comment by joyeusenoelle** [comment]
Finally updated this to include this information.
