### ISSUE TITLE
Documentation of keyboard shortcuts?

### ISSUE THREAD

**Issue by codesections** [joyeusenoelle/GuideToMastodon#4]
Would it be worth including a section on keyboard navigation?  There are the keyboard shortcuts that are documented in Mastodon itself, and then additional ones that don't seem to be documented anywhere other than in a thread: https://tootplanet.space/@YacYac/100551003949156532

[EDIT:  After some additional poking around, I found this commit <https://github.com/cobodo/mastodon/commit/692c7aa8459e4c92a6bf6a65a296f12ab9ac4843>, which seems to document all the current hotkeys.]

If this is something you'd like to add, I can write a section up and submit a pull request.

**Comment by joyeusenoelle** [comment]
Please feel free! I don't know the keyboard shortcuts well myself, so I'd appreciate the contribution. :)

**Comment by joyeusenoelle** [comment]
Since Mastodon has added a list of these in the Getting Started column, I've added a reference to that.
