### ISSUE TITLE
Possible addition: how to view the entire tree of replies to a post

### ISSUE THREAD

**Issue by AxelBoldt** [joyeusenoelle/GuideToMastodon#40]
Thanks for you guide, it's great. I have a suggestion for an addition. If you see a reply in a timeline and click on it, you'll get only the direct ancestors of this reply, as well as all descendants. But this is typically only a small part of the entire tree of replies to the original post. If you then go to the very top and click on the original post, you'll see that entire tree. If that original post lives on some server different from yours, you may have to pick "Open original page" from the ...-menu in the web interface in order to see the entire tree of replies.

**Comment by joyeusenoelle** [comment]
Sorry to leave you hanging. I've made changes reflecting your request; please let me know if I should do anything differently.
