### ISSUE TITLE
Pinafore being retired + not sure about Halcyon

### ISSUE THREAD

**Issue by lwojcik** [joyeusenoelle/GuideToMastodon#42]
Hi!

About this question: https://github.com/joyeusenoelle/GuideToMastodon#i-like-mastodon-but-i-prefer-the-way-twitter-looks

Looks [Pinafore is being retired](https://nolanlawson.com/2023/01/09/retiring-pinafore/) and I'm not sure about [the status of Halcyon](https://www.halcyon.social/) either.

There's quite a few upcoming alternatives in various states of development  and I keep finding a new one nearly every week. For example, [Semaphore](https://semaphore.social/) claims to be a spiritual successor of Pinaphore. There's also [Elk](https://elk.zone/).

I'm working on revisiting this question in the Polish version of the guide - I started with listing [all Mastodon apps and interfaces I've seen so far](https://github.com/lwojcik/Mastodon-Poradnik/wiki/Aplikacje-klienckie#www). If you like, I can submit a PR with my new take on this question here as well.

**Comment by joyeusenoelle** [comment]
Sorry to leave you hanging for so long. I'm editing my version now to indicate that Pinafore is no longer maintained, but it looks like Halcyon is back up! And please feel free to submit a PR with your new take - I'd love to see it!
