### ISSUE TITLE
Add URL verification information

### ISSUE THREAD

**Issue by MagicFab** [joyeusenoelle/GuideToMastodon#5]
Under **How do I get verified on Mastodon?** there is no mention of the profile URLs verification process.

If someone adds a link to their Mastodon profile from the URL added to their profile, the linke will show up in a small green-shadowed box.

**Comment by joyeusenoelle** [comment]
Thanks for reminding me. This is a very new feature and I'm reluctant to add information about it until more Mastodon servers have picked up the latest builds.

**Comment by joyeusenoelle** [comment]
The "How do I let people know that I am who I say I am?" section covers this now.
